[package]
name = "rustframe"
version = "0.0.1-a.0"
edition = "2021"
license = "GPL-3.0-or-later"
readme = "README.md"
description = "A simple dataframe library"

[lib]
name = "rustframe"
path = "src/lib.rs"
crate-type = ["cdylib", "lib"]

[dependencies]
chrono = "^0.4.10"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "benchmark"
harness = false