# docker-compose.yml

services:
  github-runner:
    build:
      context: .
      args:
        RUNNER_VERSION: 2.323.0
    container_name: github-runner
    env_file:
      - .env
    volumes:
      - runner-work:/home/runner/actions-runner/_work
    restart: unless-stopped

volumes:
  runner-work:
