name: docs-and-testcov

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  # pull_request:
  #   branches: [main]
  workflow_dispatch:
  workflow_run:
    workflows: ["run-benchmarks"]
    types:
      - completed

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  docs-and-testcov:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Install dependencies
        run: |
            uv pip install requests
      - name: Run CI checks
        run: |
          python .github/scripts/ci_checks.py