name: docs-and-testcov

on:
  push:
    branches: [main]
#   pull_request:
#     branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  docs-and-testcov:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
    

      - name: Build documentation
        run: cargo doc --no-deps
  
      - name: Prepare documentation for Pages
        run: |


      - name: Install Cargo binstall
        uses: cargo-bins/cargo-binstall@main

      - name: Install cargo-tarpaulin via binstall
        run: cargo binstall cargo-tarpaulin --no-confirm --locked

      - name: Generate coverage report
        run: |
          mkdir -p testcov
          cargo tarpaulin --out Html --out Json
        
      - name: Check for tarpaulin-report.html
        run: |
          if [ ! -f tarpaulin-report.html ]; then
            echo "tarpaulin-report.html not found!"
            exit 1
          fi
      
      - name: Export tarpaulin coverage badge JSON
        run: |
          jq '{schemaVersion: 1,
            label: "tarpaulin",
            message: (.coverage | tostring),
            color: "blue"}' tarpaulin-report.json > tarpaulin-badge.json

      - name: Copy files to output directory
        run: |
          mkdir output
          cp tarpaulin-report.html target/doc/rustframe/
          cp tarpaulin-report.json target/doc/rustframe/
          cp tarpaulin-badge.json target/doc/rustframe/
          echo "<meta http-equiv=\"refresh\" content=\"0; url=rustframe\">" > target/doc/index.html

      - name: Upload Pages artifact
        if: github.event_name == 'push'
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/doc/

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: actions/deploy-pages@v4
