name: run-docs-and-doc-tests

on:
  pull_request:
    branches:
      - main

jobs:
  run-docs-and-doc-tests:
    name: run-docs-and-doc-tests
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        run: rustup update stable
      - name: Run doc-tests
        run: cargo test --doc --all-features --workspace
      - name: Test docs generation
        run: cargo doc --no-deps
